development:
  adapter: postgresql
  encoding: unicode
  database: PrayWhere (copy)_development
  pool: 5
  username: tayyab
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: PrayWhere (copy)_test
  pool: 5
  username: tayyab
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: PrayWhere (copy)_production
  pool: 5
  username: tayyab
  password:
